version: '3'
services:
  db:
    build: db
    volumes:
      - kasvimuseo-run-postgres:/var/run/postgresql
  app:
    build: ..
    environment:
      KASVIMUSEO_DEBUG: 1
      PYTHONPATH: /
    links:
      - db
    volumes:
      - ${PWD}/app/local_settings.py:/local_settings.py
      - kasvimuseo-run-postgres:/var/run/postgresql
    ports:
      - "8000:8000"
