postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - postgis
postgresql_databases:
  - name: ylaneenkasvit
    owner: ylaneenkasvit
postgresql_users:
  - name: ylaneenkasvit
    password: 5tsovi25
postgresql_hba_entries:
  - type: local
    database: ylaneenkasvit
    user: ylaneenkasvit
    auth_method: md5
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}

nginx_main_template_enable: true
nginx_main_template:
  user: nginx www-data
  worker_processes: 1
  error_log:
    location: /var/log/nginx/error.log
    level: warn
  worker_connections: 1024
  http_enable: true
  http_settings:
    access_log_format:
      - name: main
        format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
    access_log_location:
      - location: /var/log/nginx/access.log
        name: main
    keepalive_timeout: 65
    cache: false
    rate_limit: false
    keyval: false
  stream_enable: false
#  template_file: nginx.conf.j2
#  conf_file_name: nginx.conf
#  conf_file_location: /etc/nginx/

nginx_http_template_enable: true
nginx_http_template:
  default:
    template_file: nginx-site.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      - domain: kasvit.ambitone.com
        app_path: "/"
        static_paths:
          /favicon.ico: /www/ylaneenkasvit/static/img/favicon.ico
      - domain: static.kasvit.ambitone.com
        static_paths:
          /: /www/ylaneenkasvit/static/
      - domain: media.kasvit.ambitone.com
        static_paths:
          /: /www/ylaneenkasvit/media/

certbot_admin_email: antti19@ambitone.com
certbot_create_if_missing: true
certbot_create_standalone_stop_services: [nginx]
certbot_certs:
  - domains:
      - media.kasvit.ambitone.com
      - kasvit.ambitone.com
      - static.kasvit.ambitone.com

app_user: kasvimuseo
django_dir: /home/kasvimuseo/.local/lib/python2.7/site-packages/ylaneenkasvit
uwsgi_socket: /home/kasvimuseo/wsgi.sock
