---
- name: Install Kasvimuseo and dependencies
  hosts: all
  remote_user: kasvimuseo
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install Python 2.7
      tags:
        - python
      apt:
        name: python-minimal
        state: present
      become: yes

    - name: Install pip 19.3.1 with a patch for issue 5780
      tags:
        - python
      pip:
        name: https://github.com/rouge8/pip/archive/gh-5780.zip
        extra_args: "--user"

    - name: Remove OS package of old pip for Python 2.7
      tags:
        - python
      apt:
        name: python-pip
        state: absent
      become: yes

#    - name: Download new pip for Python 2.7
#      tags:
#        - python
#      get_url:
#        url: https://bootstrap.pypa.io/get-pip.py
#        dest: /tmp/
#
#    - name: Install new pip for Python 2.7
#      tags:
#        - python
#      command: python2.7 /tmp/get-pip.py --user

    - name: Install the Kasvimuseo application
      tags:
        - code
      pip:
        executable: "/home/kasvimuseo/.local/bin/pip2"
        name: "git+ssh://git@bitbucket.org/akaihola/kasvimuseo.git"
        extra_args: "--user"

    - name: Create static assets directory
      tags:
        - code
        - static
      become: true
      file:
        path: /www/ylaneenkasvit
        state: directory
        owner: kasvimuseo
        group: www-data
        mode: 06770

    - name: Make manage.py executable
      tags:
        - code
        - static
      file:
        path: "{{ django_dir }}/manage.py"
        mode: 0775

    - name: Collect static assets
      tags:
        - code
        - static
      django_manage:
        command: collectstatic
        app_path: "{{ django_dir }}"
        settings: ylaneenkasvit.ylaneenkasvit_settings

    - name: Install PostgreSQL
      tags:
        - database
      become: yes
      import_role:
        name: geerlingguy.postgresql

    - name: Add Postgis extension
      tags:
        - database
        - postgis
      become: true
      become_user: "{{ postgresql_user }}"
      postgresql_ext:
        name: postgis
        db: ylaneenkasvit

    - name: Copy database backup to host
      tags:
        - database
        - restore
      copy:
        src: "{{ database_backup_to_restore }}"
        dest: /tmp/backup.sql
      when: database_backup_to_restore is defined

    - name: Restore database from backup
      tags:
        - database
        - restore
      become: true
      become_user: "{{ postgresql_user }}"
      postgresql_db:
        name: "{{ item.name }}"
        owner: "{{ item.owner | default(postgresql_user) }}"
        state: restore
        target: /tmp/backup.sql
      when: database_backup_to_restore is defined
      with_items: "{{ postgresql_databases }}"

    - name: Back up the database
      tags:
        - database
        - backup
      become: true
      become_user: "{{ postgresql_user }}"
      postgresql_db:
        name: "{{ item.name }}"
        owner: "{{ item.owner | default(postgresql_user) }}"
        state: dump
        target: /tmp/backup.sql
      when: backup_database is defined
      with_items: "{{ postgresql_databases }}"

    - name: Fetch database backup from host
      tags:
        - database
        - backup
      fetch:
        src: /tmp/backup.sql
        dest: "{{ backup_database }}"
      when: backup_database is defined

    - name: Upload media
      tags:
        - media
      become: true
      become_user: kasvimuseo
      synchronize:
        src: ../media
        dest: /www/ylaneenkasvit/
        archive: false
        recursive: true
        rsync_path: /usr/bin/rsync
      when: upload_media is defined

    - name: Install NGINX
      tags:
        - web
        - nginx
      become: yes
      import_role:
        name: nginxinc.nginx

    - name: Configure Certbot
      tags:
        - web
        - certbot
      become: yes
      import_role:
        name: geerlingguy.certbot

    - name: uWSGI
      tags:
        - web
        - uwsgi
      become: yes
      import_role:
        name: akaihola.uwsgi
