---
- name: Install Kasvimuseo and dependencies
  hosts: all
  remote_user: kasvimuseo
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install Python 2.7
      tags:
        - python
      apt:
        name: python-minimal
        state: present
      become: yes

    - name: Install pip for Python 2.7
      tags:
        - python
      apt:
        name: python-pip
        state: present
      become: yes

    - name: Install the Kasvimuseo application
      tags:
        - code
      pip:
        executable: "pip2"
        name: "git+ssh://git@bitbucket.org/akaihola/kasvimuseo.git"
        extra_args: "--user"

    - name: Create static assets directory
      tags:
        - code
      become: true
      file:
        path: /www/ylaneenkasvit
        state: directory
        owner: kasvimuseo
        group: www-data

    - name: Make manage.py executable
      tags:
        - code
      file:
        path: "{{ django_dir }}/manage.py"
        mode: 0775

    - name: Collect static assets
      tags:
        - code
        - static
      django_manage:
        command: collectstatic
        app_path: "{{ django_dir }}"
        settings: ylaneenkasvit.ylaneenkasvit_settings

    - name: Install PostgreSQL
      tags:
        - database
      become: yes
      import_role:
        name: geerlingguy.postgresql

    - name: Add Postgis extension
      tags:
        - database
        - postgis
      become: true
      become_user: "{{ postgresql_user }}"
      postgresql_ext:
        name: postgis
        db: ylaneenkasvit

    - name: Install NGINX
      tags:
        - web
        - nginx
      become: yes
      import_role:
        name: nginxinc.nginx

    - name: Configure Certbot
      tags:
        - web
        - certbot
      become: yes
      import_role:
        name: geerlingguy.certbot

    - name: uWSGI
      tags:
        - web
        - uwsgi
      become: yes
      import_role:
        name: akaihola.uwsgi
