[uwsgi]
wsgi-file = ylaneenkasvit/wsgi.py
callable = application
socket = /home/kasvimuseo/wsgi.sock
chmod-socket = 660
uid = kasvimuseo
gid = www-data
chdir = /home/kasvimuseo
home = /home/kasvimuseo
processes = 10
plugins = python,logfile
;req-logger = file:/home/kasvimuseo/uwsgi.access.log
;logger = file:/home/kasvimuseo/uwsgi.error.log
